spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/melhoremcasa_api
spring.datasource.username=postgres
spring.datasource.password=senhor21
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (útil para debug)
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG